config/routes.rb
Rails.application.routes.draw do
  root 'repository#form'

  post 'repository/index' => "repository#index"

end

app/models/user.rb
class User

  attr_reader :name, :username

  def initialize(username)
    @username = username
    @user_info = get_user_info
    @name = name
    @repos = get_repos
    @time_now = get_time
  end

  private def get_user_info
    HTTParty.get("https://api.github.com/users/#{@username}",
      headers: {"Authorization" => "token #{ENV["GITHUB_KEY"]}",
                   "User-Agent" => "cruznunez"
      }
    )

  end

  private def get_repos
    HTTParty.get("https://api.github.com/users/#{@username}/repos",
      headers: {"Authorization" => "token #{ENV["GITHUB_KEY"]}",
                   "User-Agent" => "cruznunez"
      }
    )
  end

  private def get_time
    Time.now
  end

  def pic
    @user_info["avatar_url"]
  end

  def name
    @user_info["name"]
  end

  def email
    @user_info["email"]
  end

  def joined
    hash = {
      "01" => "Jan", "02" => "Feb", "03" => "Mar", "04" => "Apr", "05" => "May",
      "06" => "Jun", "07" => "Jul", "08" => "Aug", "09" => "Sep", "10" => "Oct",
      "11" => "Nov", "12" => "Dec"
    }
    string = @user_info["created_at"]
    year = string[0..3]
    month = hash[string[5..6]]
    day = string[8..9]
    "Joined on #{month} #{day}, #{year}"
  end

  def location
    @user_info["location"]
  end

  def org
    @user_info["company"]
  end

  def followers
    @user_info["followers"]
  end

  def following
    @user_info["following"]
  end

  def stargazers(num)
    @repos[num]["stargazers_count"]
  end

  def forks(num)
    @repos[num]["forks"]
  end

  def repo_len
    @repos.length
  end

  def repo_name(num)
    @repos[num]["name"]
  end

  def repo_updated_at(num)
    update_str = @repos[num]["pushed_at"]

    old_hour = (update_str[11..12].to_i) - 4
    hour = (old_hour >= 0) ? old_hour : ((24 + old_hour).to_s)
    old_day = update_str[8..9]
    day = (old_hour) > 0 ? old_day : ((old_day.to_i - 1).to_s)
    old_month = update_str[5..6]
    month = day.to_i > 0 ? old_month : old
    year = update_str[0..3]
    min = update_str[14..15]
    sec = update_str[17..18]
    update_time = Time.new(year, month, day, hour, min, sec)
    # update_time = github_update_str.to_date
    time_elapsed_seconds = @time_now - update_time
    time_elapsed_seconds
    time_elapsed_days_unrounded = (time_elapsed_seconds.to_f / (24 * 60 * 60).to_f)
    time_elapsed_days = time_elapsed_days_unrounded.round
    "Updated #{time_elapsed_days} days ago"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/repository_controller.rb
class RepositoryController < ApplicationController
  def form
  end

  def index
    @user = User.new(params[:user_name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/repository_helper.rb
module RepositoryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GithubProfilePage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= yield %>
</html>

app/views/repository/form.html.erb
<body class="black">

<div class="body">
<h1>Soon to be "Form Page"</h1>
<p>blah blah blah I haven't worked on this page yet <span style="font-size:256px">😜</span>.</p>

<%= form_tag repository_index_path do %>
  <%= text_field_tag :user_name %>
  <%= submit_tag "search with username" %>
<% end %>

<center>
  <script src="http://h2.flashvortex.com/display.php?id=2_1433309366_43888_495_0_712_164_10_2_4" type="text/javascript"></script></body>
</center>

app/views/repository/index.html.erb
<body>

<div class="header header-logged-out" role="banner">
  <div class="container clearfix">

    <a class="header-logo-wordmark" href="https://github.com/" data-ga-click="(Logged out) Header, go to homepage, icon:logo-wordmark">
      <span style="font-family:monospace;font-size:30px">GitHub</span>
    </a>

    <div class="header-actions" role="navigation">
        <a class="btn btn-primary" href="/join" data-ga-click="(Logged out) Header, clicked Sign up, text:sign-up">Sign up</a>
      <a class="btn" href="/login?return_to=%2Fcruznunez%3Ftab%3Drepositories" data-ga-click="(Logged out) Header, clicked Sign in, text:sign-in">Sign in</a>
    </div>

    <div class="site-search  js-site-search">
      <form action="repository/index" method="post" name="username"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden"></div>
  <label class="js-chromeless-input-container form-control">
    <div class="scope-badge">This repository</div>
    <input type="text" class="js-site-search-focus  chromeless-input" data-hotkey="s" name="q" placeholder="Search GitHub" data-global-scope-placeholder="Search GitHub" data-repo-scope-placeholder="Search" tabindex="1" autocapitalize="off">
  </label>
</form>
    </div>

      <ul class="header-nav left" role="navigation">
          <li class="header-nav-item">
            <a class="header-nav-link" href="/explore" data-ga-click="(Logged out) Header, go to explore, text:explore">Explore</a>
          </li>
          <li class="header-nav-item">
            <a class="header-nav-link" href="/features" data-ga-click="(Logged out) Header, go to features, text:features">Features</a>
          </li>
          <li class="header-nav-item">
            <a class="header-nav-link" href="https://enterprise.github.com/" data-ga-click="(Logged out) Header, go to enterprise, text:enterprise">Enterprise</a>
          </li>
          <li class="header-nav-item">
            <a class="header-nav-link" href="/blog" data-ga-click="(Logged out) Header, go to blog, text:blog">Blog</a>
          </li>
      </ul>

  </div>
</div>

<div id="start-of-content" class="accessibility-aid"></div>
<div class="site clearfix" role="main">

  <div id="site-container" class="context-loader-container" data-pjax-container="">




    <div class="container">
      <div class="columns profilecols">
        <div class="column one-fourth vcard" itemscope="" itemtype="http://schema.org/Person">
            <a href="https://avatars1.githubusercontent.com/u/8742021?v=3&amp;s=400" aria-hidden="true" class="vcard-avatar" itemprop="image"><img alt="" class="avatar" height="230" src="<%= @user.pic %>" width="230"></a>
              <h1 class="vcard-names">
                  <span class="vcard-fullname" itemprop="name"><%= @user.name %></span>
                  <span class="vcard-username" itemprop="additionalName"><%= @user.username %></span>
              </h1>



        <ul class="vcard-details">
          <% if @user.org != "" %>
            <li class="vcard-detail" itemprop="worksFor" title="The Iron Yard"><span class="octicon octicon-organization"></span><%= @user.org %></li>
            <li class="vcard-detail" itemprop="homeLocation" title="Durham, NC"><span class="octicon octicon-location"></span><%= @user.location %></li>
          <% else %>
            <li class="vcard-detail" itemprop="homeLocation" title="Durham, NC"><span class="octicon octicon-location"></span><%= @user.location %></li>
            <li class="vcard-detail"><span class="octicon octicon-mail"></span><a class="email" href="mailto:<%= @user.email %>"><%= @user.email %></a></li>
          <% end %>
          <li class="vcard-detail"><span class="octicon octicon-clock"></span><span class="join-label"><%= @user.joined %></time></li>
        </ul>


          <div class="vcard-stats">
            <a class="vcard-stat" href="/cruznunez/followers">
              <strong class="vcard-stat-count"><%= @user.followers %></strong>
              <span class="text-muted">Followers</span>
            </a>
            <a class="vcard-stat" href="/stars/cruznunez">
              <strong class="vcard-stat-count">0</strong>
              <span class="text-muted">Starred</span>
            </a>
            <a class="vcard-stat" href="/cruznunez/following">
              <strong class="vcard-stat-count"><%= @user.following %></strong>
              <span class="text-muted">Following</span>
            </a>
          </div>

        </div>

        <div class="column three-fourths">


          <div class="tabnav">
              <div class="right">
                  <span class="user-following-container">
        <span class="follow">
          <a href="/login?return_to=%2Fcruznunez%3Ftab%3Drepositories" class="btn btn-sm btn-primary">
            <span class="octicon octicon-person"></span>
            Follow
          </a>
        </span>
      </span>

              </div>

            <nav class="tabnav-tabs" data-pjax="" role="navigation">
              <a href="/cruznunez" class="tabnav-tab ">
                <span class="octicon octicon-diff-added"></span>
                Contributions
              </a>
              <a href="/cruznunez?tab=repositories" class="tabnav-tab selected">
                <span class="octicon octicon-repo"></span>
                Repositories
              </a>
              <a href="/cruznunez?tab=activity" class="tabnav-tab ">
                <span class="octicon octicon-rss"></span>
                Public activity
              </a>
            </nav>
          </div>

          <div class="tab-content js-repo-filter">

      <div class="repo-tab">
        <div class="filter-bar">
          <ul class="repo_filterer">
              <li><a href="#" class="repo_filter js-repo-filter-tab" data-filter=".mirror">Mirrors</a></li>
            <li><a href="#" class="repo_filter js-repo-filter-tab" data-filter=".fork">Forks</a></li>
            <li><a href="#" class="repo_filter js-repo-filter-tab" data-filter=".source">Sources</a></li>
            <li class="all_repos"><a href="#" class="repo_filter js-repo-filter-tab filter-selected" data-filter=".public, .private">All</a></li>
          </ul>

          <form accept-charset="UTF-8" action="/search" class="repo-search" method="get" role="search"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"></div>
            <input type="hidden" name="user" value="cruznunez">
            <input type="text" id="your-repos-filter" name="q" class="filter_input js-filterable-field" placeholder="Find a repository…" tabindex="2">
            <input type="submit" value="Search" class="btn">
    </form>    </div>

    <ul class="repo-list js-repo-list" data-filterable-for="your-repos-filter" data-filterable-type="substring">

      <% array = (0..(@user.repo_len-1)).to_a.reverse%>
      <% array.each do |num| %>
        <li class="repo-list-item public source">
          <div class="repo-list-stats">
              Ruby
            <a class="repo-list-stat-item tooltipped tooltipped-s" href="/cruznunez/github_profile_page/stargazers" aria-label="Stargazers">
              <span class="octicon octicon-star"></span>
              <%= @user.stargazers(num)%>
            </a>
            <a class="repo-list-stat-item tooltipped tooltipped-s" href="/cruznunez/github_profile_page/network" aria-label="Forks">
              <span class="octicon octicon-git-branch"></span>
              <%= @user.forks(num) %>
            </a>
          </div>

          <h3 class="repo-list-name">
            <a href="/cruznunez/voting_api">
              <%= @user.repo_name(num) %> </a>
          </h3>

          <p class="repo-list-meta">
            <%= @user.repo_updated_at(num) %>
          </p>

          <div class="participation-graph">
            <svg class="bars" width="640" height="80"></svg>
          </div>
        </li>
      <% end %>
    </ul>

      </div>

          </div>
        </div>

      </div>
    </div>

  </div>
  <div class="modal-backdrop"></div>
</div>
</body>